/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QnAForumInterface;

import CustomControls.SimpleScrollPane;
import DataObjects.*;
import QnAForumDatabase.Database;

import QnAForumInterface.ProfileBoardPackage.ProfileBoard;
import Resources.ResourceManager;

import javax.swing.*;
import javax.swing.plaf.basic.BasicComboBoxUI;
import java.awt.*;
import java.awt.event.*;

/**
 * @author AJ
 */
public class AskBoard extends JPanel {

    private JPanel askContainer;
    private JButton backBtn;
    private JTextArea body;
    private CustomControls.RoundedJPanel bodyContainer;
    private JLabel bodyLabel;
    private SimpleScrollPane bodyScrollPane;
    private JPanel buttonHolder;
    private CustomControls.RoundedJPanel container;
    private SimpleScrollPane containerScrollPane;
    private JTextArea head;
    private CustomControls.RoundedJPanel headContainer;
    private JLabel headLabel;
    private SimpleScrollPane headScrollPane;
    private JButton searchBtn;
    private JButton submitBtn;
    private JComboBox<String> tag;
    private CustomControls.RoundedJPanel tagContainer;
    private JLabel tagText;
    private JPanel tagsDisplay;
    private JLabel tagsErrorLabel;
    private JLabel tagsLabel;
    private CustomControls.RoundedJPanel tagsRoundedPanel;
    private JLabel titleLabel;
    private JPanel userHolder;
    private JLabel userName;
    private JLabel userProfile;
    private String questionID;
    /**
     * Creates new form AskBoard
     */
    public AskBoard() {
        initComponents();
    }

    public static AskBoard init(String username, String userProfileIndex, String questioner, String questionHead, String questionBody, String questionID) {
        AskBoard board = new AskBoard();

        board.userName.setText(username);
        ResourceManager.setProfileIcon(userProfileIndex, board.userProfile, ResourceManager.REGULAR);
        board.headLabel.setText(questioner + ": " + questionHead);
        board.head.setText(questionBody);
        board.head.setEditable(false);
        board.tagsDisplay.setVisible(false);
        board.tagContainer.setVisible(false);
        board.searchBtn.setVisible(false);
        board.bodyLabel.setText("Answer:");
        board.submitBtn.setText("Submit Answer");
        board.titleLabel.setText("Respond to Question");
        board.bodyLabel.setIcon(ResourceManager.getIcon("answer_pressed", ResourceManager.MINI));
        board.questionID = questionID;
        return board;
    }

    public static AskBoard init(String username, String userProfileIndex) {
        AskBoard board = new AskBoard();

        board.userName.setText(username);
        ResourceManager.setProfileIcon(userProfileIndex, board.userProfile, ResourceManager.REGULAR);
        board.headLabel.setText("Question Head - Keep it simple");
        board.bodyLabel.setText("Question Body - Elaborate your Question");
        board.submitBtn.setText("Ask a Question");
        board.tagText.setText("");
        board.tagsRoundedPanel.setVisible(false);
        board.questionID = null;
        return board;
    }

    public void clearTag() {
        String[] tags = tagText.getText().split(" \\| ");


        if (tags.length <= 1) {
            tagText.setText("");
            tagsRoundedPanel.setVisible(false);
            return;
        }

        StringBuilder clearedTagText = new StringBuilder();
        for (int i = 0; i < tags.length - 1; i++) {
            clearedTagText.append(tags[i]);
            if (i < tags.length - 2) {
                clearedTagText.append(" | ");
            }
        }
        tagText.setText(clearedTagText.toString());
    }

    public void addTag(String tag) {
        tag = tag.replaceAll(" ", "");
        String[] tags = tagText.getText().split(" \\| ");
        boolean containsTag = false;

        for (String checkTag : tags) {
            if (checkTag.equals(tag)) {
                containsTag = true;
                break;
            }
        }

        if (!tag.matches("^[a-zA-Z0-9]+$") || containsTag) return;

        tagsRoundedPanel.setVisible(true);
        tag = tagText.getText().isEmpty() ? tag : tagText.getText() + " | " + tag;
        tagText.setText(tag);
        tagsRoundedPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        container = new CustomControls.RoundedJPanel();
        userHolder = new JPanel();
        userProfile = new JLabel();
        userName = new JLabel();
        buttonHolder = new JPanel();
        searchBtn = new JButton();
        submitBtn = new JButton();
        backBtn = new JButton();
        titleLabel = new JLabel();
        containerScrollPane = new SimpleScrollPane();
        containerScrollPane.getVerticalScrollBar().setUnitIncrement(10);
        askContainer = new JPanel();
        headLabel = new JLabel();
        headContainer = new CustomControls.RoundedJPanel();
        headScrollPane = new SimpleScrollPane();
        headScrollPane.getVerticalScrollBar().setUnitIncrement(2);
        head = new JTextArea();
        bodyLabel = new JLabel();
        bodyContainer = new CustomControls.RoundedJPanel();
        bodyScrollPane = new SimpleScrollPane(null);
        bodyScrollPane.getVerticalScrollBar().setUnitIncrement(5);
        body = new JTextArea();
        tagsErrorLabel = new JLabel();
        tagsDisplay = new JPanel();
        tagsLabel = new JLabel();
        tagsRoundedPanel = new CustomControls.RoundedJPanel();
        tagText = new JLabel();
        tagContainer = new CustomControls.RoundedJPanel();
        tag = new JComboBox<>();

        setBackground(ResourceManager.getColor("base"));
        setLayout(new GridBagLayout());

        container.setBackground(ResourceManager.getColor("main"));
        container.setCornerRadius(90);
        container.setPreferredSize(new Dimension(400, 120));
        container.setLayout(new GridBagLayout());

        userHolder.setOpaque(false);
        userHolder.setLayout(new GridBagLayout());

        userProfile.setIcon(ResourceManager.getIcon("user_profile", ResourceManager.REGULAR)
        );
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.insets = new Insets(0, 20, 0, 20);
        userHolder.add(userProfile, gridBagConstraints);

        userName.setForeground(ResourceManager.getColor("text_fg_light"));
        userName.setText("Username");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new Insets(0, 20, 0, 20);
        userHolder.add(userName, gridBagConstraints);
        userName.setFont(ResourceManager.getFont("inter_semibold.36"));

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.weighty = 1.0;
        container.add(userHolder, gridBagConstraints);

        buttonHolder.setOpaque(false);
        buttonHolder.setLayout(new GridBagLayout());

        searchBtn.setForeground(ResourceManager.getColor("text_fg_light"));
        searchBtn.setIcon(ResourceManager.getIcon("search_default", ResourceManager.MINI));
        searchBtn.setText("Search");
        searchBtn.setBorderPainted(false);
        searchBtn.setContentAreaFilled(false);
        searchBtn.setFocusPainted(false);
        searchBtn.setPressedIcon(ResourceManager.getIcon("search_pressed", ResourceManager.MINI)
        );
        searchBtn.setRolloverIcon(ResourceManager.getIcon("search_rollover", ResourceManager.MINI)
        );
        searchBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new Insets(20, 40, 5, 40);
        buttonHolder.add(searchBtn, gridBagConstraints);
        searchBtn.setFont(ResourceManager.getFont("inter_regular.22"));

        submitBtn.setForeground(ResourceManager.getColor("text_fg_light"));
        submitBtn.setIcon(ResourceManager.getIcon("submit_default", ResourceManager.MINI));
        submitBtn.setText("Submit");
        submitBtn.setBorderPainted(false);
        submitBtn.setContentAreaFilled(false);
        submitBtn.setFocusPainted(false);
        submitBtn.setPressedIcon(ResourceManager.getIcon("submit_pressed", ResourceManager.MINI)
        );
        submitBtn.setRolloverIcon(ResourceManager.getIcon("submit_rollover", ResourceManager.MINI)
        );
        submitBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new Insets(5, 40, 5, 40);
        buttonHolder.add(submitBtn, gridBagConstraints);
        submitBtn.setFont(ResourceManager.getFont("inter_regular.22"));

        backBtn.setForeground(ResourceManager.getColor("text_fg_light"));
        backBtn.setIcon(ResourceManager.getIcon("home_default", ResourceManager.MINI));
        backBtn.setText("Back");
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setFocusPainted(false);
        backBtn.setPressedIcon(ResourceManager.getIcon("home_pressed", ResourceManager.MINI)
        );
        backBtn.setRolloverIcon(ResourceManager.getIcon("home_rollover", ResourceManager.MINI)
        );
        backBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new Insets(5, 40, 20, 40);
        buttonHolder.add(backBtn, gridBagConstraints);
        backBtn.setFont(ResourceManager.getFont("inter_regular.22"));

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = GridBagConstraints.SOUTH;
        container.add(buttonHolder, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        add(container, gridBagConstraints);

        titleLabel.setHorizontalAlignment(SwingConstants.CENTER);
        titleLabel.setText("Ask Question");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(20, 20, 20, 20);
        add(titleLabel, gridBagConstraints);
        titleLabel.setFont(ResourceManager.getFont("inter_semibold.32"));
        titleLabel.setForeground(ResourceManager.getColor("text_fg_dark"));

        containerScrollPane.setBackground(ResourceManager.getColor("base"));
        containerScrollPane.setBorder(null);
        containerScrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        containerScrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        containerScrollPane.setAutoscrolls(true);
        containerScrollPane.setOpaque(false);

        askContainer.setBackground(ResourceManager.getColor("base"));
        askContainer.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        askContainer.setLayout(new GridBagLayout());

        headLabel.setIcon(ResourceManager.getIcon("question_pressed", ResourceManager.MINI)
        );
        headLabel.setText("Question Head - Keep it simple");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        askContainer.add(headLabel, gridBagConstraints);
        headLabel.setFont(ResourceManager.getFont("inter_regular.24"));
        headLabel.setForeground(ResourceManager.getColor("text_fg_dark"));

        headContainer.setBackground(ResourceManager.getColor("main_dark"));
        headContainer.setCornerRadius(90);
        headContainer.setLimitRadius(false);
        headContainer.setLayout(new BorderLayout());

        headScrollPane.setBorder(BorderFactory.createEmptyBorder(15, 15, 20, 15));
        headScrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        headScrollPane.setMinimumSize(new Dimension(23, 90));
        headScrollPane.setOpaque(false);
        headScrollPane.setPreferredSize(new Dimension(486, 100));

        head.setBackground(ResourceManager.getColor("main_dark"));
        head.setColumns(20);
        head.setForeground(ResourceManager.getColor("text_fg_light"));
        head.setLineWrap(true);
        head.setRows(5);
        head.setText("Head...");
        head.setWrapStyleWord(true);
        head.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        head.setCaretColor(ResourceManager.getColor("base"));
        head.setMinimumSize(new Dimension(0, 0));
        head.setOpaque(false);
        head.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent evt) {
                headFocusGained(evt);
            }

            public void focusLost(FocusEvent evt) {
                headFocusLost(evt);
            }
        });
        headScrollPane.setViewportView(head);
        head.setFont(ResourceManager.getFont("inter_regular.24"));

        headContainer.add(headScrollPane, BorderLayout.CENTER);
        headScrollPane.getViewport().setOpaque(false);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        askContainer.add(headContainer, gridBagConstraints);

        bodyLabel.setIcon(ResourceManager.getIcon("question_pressed", ResourceManager.MINI)
        );
        bodyLabel.setText("Question Body - Elaborate your Question");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(40, 0, 0, 0);
        askContainer.add(bodyLabel, gridBagConstraints);
        bodyLabel.setFont(ResourceManager.getFont("inter_regular.24"));
        bodyLabel.setForeground(ResourceManager.getColor("text_fg_dark"));

        bodyContainer.setBackground(ResourceManager.getColor("main_dark"));
        bodyContainer.setCornerRadius(90);
        bodyContainer.setLayout(new BorderLayout());

        bodyScrollPane.setBorder(BorderFactory.createEmptyBorder(15, 15, 20, 15));
        bodyScrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        bodyScrollPane.setMinimumSize(new Dimension(23, 100));
        bodyScrollPane.setOpaque(false);
        bodyScrollPane.setPreferredSize(new Dimension(486, 200));

        body.setBackground(ResourceManager.getColor("main_dark"));
        body.setColumns(20);
        body.setForeground(ResourceManager.getColor("text_fg_light"));
        body.setLineWrap(true);
        body.setRows(5);
        body.setText("Body...");
        body.setWrapStyleWord(true);
        body.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        body.setCaretColor(ResourceManager.getColor("base"));
        body.setMinimumSize(new Dimension(0, 0));
        body.setOpaque(false);
        body.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent evt) {
                bodyFocusGained(evt);
            }

            public void focusLost(FocusEvent evt) {
                bodyFocusLost(evt);
            }
        });
        bodyScrollPane.setViewportView(body);
        body.setFont(ResourceManager.getFont("inter_regular.24"));

        bodyContainer.add(bodyScrollPane, BorderLayout.CENTER);
        bodyScrollPane.getViewport().setOpaque(false);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(0, 0, 40, 0);
        askContainer.add(bodyContainer, gridBagConstraints);

        tagsErrorLabel.setForeground(ResourceManager.getColor("error"));
        tagsErrorLabel.setText("Add atleast 3 tags!");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(0, 20, 0, 0);
        askContainer.add(tagsErrorLabel, gridBagConstraints);
        tagsErrorLabel.setFont(ResourceManager.getFont("inter_semibold.16"));
        tagsErrorLabel.setVisible(false);

        tagsDisplay.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 5));

        tagsLabel.setIcon(ResourceManager.getIcon("tag_pressed", ResourceManager.MINI)
        );
        tagsLabel.setText("Tags");
        tagsLabel.setToolTipText("");
        tagsDisplay.add(tagsLabel);
        tagsLabel.setFont(ResourceManager.getFont("inter_regular.24"));

        tagsRoundedPanel.setBackground(ResourceManager.getColor("main"));
        tagsRoundedPanel.setBorder(BorderFactory.createEmptyBorder(8, 10, 8, 10));
        tagsRoundedPanel.setCornerRadius(50);
        tagsRoundedPanel.setLimitRadius(false);
        tagsRoundedPanel.addMouseListener(new MouseAdapter() {
            public void mouseReleased(MouseEvent evt) {
                tagsRoundedPanelMouseReleased(evt);
            }
        });
        tagsRoundedPanel.setLayout(new BoxLayout(tagsRoundedPanel, BoxLayout.X_AXIS));

        tagText.setForeground(ResourceManager.getColor("text_fg_light"));
        tagText.setText("tag1 | tag2 | tag3");
        tagText.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        tagsRoundedPanel.add(tagText);
        tagText.setFont(ResourceManager.getFont("inter_regular.22"));

        tagsDisplay.add(tagsRoundedPanel);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        askContainer.add(tagsDisplay, gridBagConstraints);

        tagContainer.setBackground(ResourceManager.getColor("main_dark"));
        tagContainer.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        tagContainer.setCornerRadius(90);
        tagContainer.setLayout(new BorderLayout());

        tag.setBackground(tagContainer.getBackground());
        tag.setEditable(true);
        tag.setForeground(ResourceManager.getColor("text_fg_light"));
        tagContainer.add(tag, BorderLayout.PAGE_END);
        tag.setFont(ResourceManager.getFont("inter_regular.24"));

        tag.setUI(new BasicComboBoxUI() {
            @Override
            protected JButton createArrowButton() {
                return new JButton() {
                    @Override
                    public int getWidth() {
                        return 0;
                    }
                };
            }
        });
        tag.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        tag.setMaximumRowCount(3);

        JTextField textField = (JTextField) tag.getEditor().getEditorComponent();
        textField.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent evt) {
                tagsLabel.setIcon(ResourceManager.getIcon("tag_default", ResourceManager.MINI));
            }

            public void focusLost(FocusEvent evt) {
                tagsLabel.setIcon(ResourceManager.getIcon("tag_pressed", ResourceManager.MINI));
            }
        });
        textField.setForeground(Color.white);
        textField.setCaretColor(Color.white);
        textField.setBackground(ResourceManager.getColor("main_dark"));

        textField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_DOWN ||
                        e.getKeyCode() == KeyEvent.VK_UP) {
                    revalidate();
                    repaint();
                    return;
                }

                String text = textField.getText();
                tag.removeAllItems();
                tag.addItem(text);

                if (e.getKeyCode() == KeyEvent.VK_ENTER ||
                        e.getKeyCode() == KeyEvent.VK_TAB) {
                    addTag(textField.getText());
                    textField.setText("");
                    revalidate();
                    repaint();
                    return;
                }

                for (String suggestion : getTags()) {
                    if (suggestion.equalsIgnoreCase(text)) {
                        tag.removeAllItems();
                        tag.addItem(text);
                        tag.addItem(suggestion);
                    } else if (suggestion.toLowerCase().startsWith(text.toLowerCase())) {
                        tag.addItem(suggestion);
                    }

                }
                tag.setPopupVisible(tag.getItemCount() > 1);
                tag.revalidate();
                tag.repaint();
                revalidate();
                repaint();
            }
        });

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        askContainer.add(tagContainer, gridBagConstraints);

        containerScrollPane.setViewportView(askContainer);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        add(containerScrollPane, gridBagConstraints);
        containerScrollPane.getViewport().setOpaque(false);
        containerScrollPane.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));

    }// </editor-fold>//GEN-END:initComponents

    private void switchToProfile() {
        QnAForum.setContent(ProfileBoard.init(userName.getText()));
    }

    private boolean isAskBoard() {
        return questionID == null;
    }

    private void submitBtnActionPerformed(ActionEvent evt) {
        String[] tags = tagText.getText().split(" \\| ");
        if (isAskBoard() && tags.length < 3) {
            tagsErrorLabel.setVisible(true);
            return;
        }

        DataObject dataObject;
        String userID = Database.getData(UserDataObject.TABLE, UserDataObject.userIDKey(),
                UserDataObject.usernameKey(), userName.getText(), true)[0];

        if (isAskBoard()) {
            String headText = head.getText().trim();
            String bodyText = body.getText().trim();

            if (headText.isEmpty() || bodyText.isEmpty()) return;
            dataObject = new QuestionDataObject(headText, bodyText, userID);

            String questionID = Database.insertData(dataObject);

            for (String tag : tags) {
                Database.insertData(new TagDataObject(tag, questionID));
            }
        } else {
            String bodyText = body.getText().trim();

            if (bodyText.isEmpty()) return;
            dataObject = new AnswerDataObject(body.getText().trim(), userID, questionID);
            Database.insertData(dataObject);
        }

        switchToProfile();
    }

    private void backBtnActionPerformed(ActionEvent evt) {
        switchToProfile();
    }

    private void bodyFocusGained(FocusEvent evt) {
        if (isAskBoard())
            bodyLabel.setIcon(ResourceManager.getIcon("question_default", ResourceManager.MINI));
        else
            bodyLabel.setIcon(ResourceManager.getIcon("answer_default", ResourceManager.MINI));
    }

    private void bodyFocusLost(FocusEvent evt) {
        if (isAskBoard())
            bodyLabel.setIcon(ResourceManager.getIcon("question_pressed", ResourceManager.MINI));
        else
            bodyLabel.setIcon(ResourceManager.getIcon("answer_pressed", ResourceManager.MINI));
    }

    private void headFocusGained(FocusEvent evt) {
        headLabel.setIcon(ResourceManager.getIcon("question_default", ResourceManager.MINI));
    }

    private void headFocusLost(FocusEvent evt) {
        headLabel.setIcon(ResourceManager.getIcon("question_pressed", ResourceManager.MINI));
    }

    private void tagsRoundedPanelMouseReleased(MouseEvent evt) {
        clearTag();
    }

    private void searchBtnActionPerformed(ActionEvent evt) {
        QnAForum.setContent(SearchBoard.init(userName.getText(), userProfile.getName()));
    }

    private String[] getTags() {
        return TagExtractor.extractPotentialTags(head.getText() + " " + body.getText());
    }
}
