/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QnAForumInterface;


import QnAForumInterface.ProfileBoardPackage.ProfileBoard;
import Resources.ResourceManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;


/**
 * @author AJ
 */
public class OptionsPanel extends JPanel {

    protected static final Icon[] arrowDown;
    protected static final Icon[] arrowUp;

    static {
        int size = 32;
        arrowDown = new Icon[]{
                ResourceManager.getIcon("arrowD_default", size),
                ResourceManager.getIcon("arrowD_pressed", size),
                ResourceManager.getIcon("arrowD_rollover", size)
        };
        arrowUp = new Icon[]{
                ResourceManager.getIcon("arrowU_default", size),
                ResourceManager.getIcon("arrowU_pressed", size),
                ResourceManager.getIcon("arrowU_rollover", size)
        };
    }

    private JButton answerButton;
    private JButton askBtn;
    private JPanel buttonHolder;
    private JButton displayAnswerBtn;
    private JButton profileBtn;
    private JButton searchBtn;
    private JLabel userName;
    private JLabel userProfile;
    /**
     * Creates new form OptionsPanel
     */
    public OptionsPanel() {
        initComponents();
    }

    public void setUserInfo(String username, String profileIndex, boolean isAnswerOptionVisible) {
        this.userName.setText(username);
        ResourceManager.setProfileIcon(profileIndex, userProfile, ResourceManager.REGULAR);
        this.answerButton.setVisible(isAnswerOptionVisible);
    }

    public String getUsername() {
        return userName.getText();
    }

    public String getUserProfileIndex() {
        return userProfile.getName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        userProfile = new JLabel();
        userName = new JLabel();
        buttonHolder = new JPanel();
        profileBtn = new JButton();
        searchBtn = new JButton();
        askBtn = new JButton();
        answerButton = new JButton();
        displayAnswerBtn = new JButton();

        setBackground(ResourceManager.getColor("base"));
        setLayout(new GridBagLayout());

        userProfile.setIcon(ResourceManager.getIcon("user_profile", ResourceManager.SMALL));
        userProfile.setVerticalAlignment(SwingConstants.BOTTOM);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(60, 25, 0, 25);
        add(userProfile, gridBagConstraints);

        userName.setText("Username");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(0, 25, 25, 25);
        add(userName, gridBagConstraints);
        userName.setFont(ResourceManager.getFont("inter_bold.28"));
        userName.setForeground(ResourceManager.getColor("text_fg_dark"));

        buttonHolder.setOpaque(false);
        buttonHolder.setLayout(new GridBagLayout());

        profileBtn.setBackground(getBackground());
        profileBtn.setIcon(ResourceManager.getIcon("home_default", ResourceManager.MINI));
        profileBtn.setText("Profile");
        profileBtn.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        profileBtn.setBorderPainted(false);
        profileBtn.setContentAreaFilled(false);
        profileBtn.setFocusPainted(false);
        profileBtn.setPressedIcon(ResourceManager.getIcon("home_pressed", ResourceManager.MINI));
        profileBtn.setRolloverIcon(ResourceManager.getIcon("home_rollover", ResourceManager.MINI));
        profileBtn.addActionListener(evt -> profileBtnActionPerformed(evt));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        buttonHolder.add(profileBtn, gridBagConstraints);
        profileBtn.setFont(ResourceManager.getFont("inter_regular.22"));
        profileBtn.setForeground(ResourceManager.getColor("text_fg_dark"));

        searchBtn.setBackground(getBackground());
        searchBtn.setIcon(ResourceManager.getIcon("search_default", ResourceManager.MINI));
        searchBtn.setText("Search");
        searchBtn.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        searchBtn.setBorderPainted(false);
        searchBtn.setContentAreaFilled(false);
        searchBtn.setFocusPainted(false);
        searchBtn.setPressedIcon(ResourceManager.getIcon("search_pressed", ResourceManager.MINI));
        searchBtn.setRolloverIcon(ResourceManager.getIcon("search_rollover", ResourceManager.MINI));
        searchBtn.addActionListener(evt -> searchBtnActionPerformed(evt));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        buttonHolder.add(searchBtn, gridBagConstraints);
        searchBtn.setFont(ResourceManager.getFont("inter_regular.22"));
        searchBtn.setForeground(ResourceManager.getColor("text_fg_dark"));

        askBtn.setBackground(getBackground());
        askBtn.setIcon(ResourceManager.getIcon("question_default", ResourceManager.MINI));
        askBtn.setText("Ask");
        askBtn.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        askBtn.setBorderPainted(false);
        askBtn.setContentAreaFilled(false);
        askBtn.setFocusPainted(false);
        askBtn.setPressedIcon(ResourceManager.getIcon("question_pressed", ResourceManager.MINI));
        askBtn.setRolloverIcon(ResourceManager.getIcon("question_rollover", ResourceManager.MINI));
        askBtn.addActionListener(evt -> askBtnActionPerformed(evt));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        buttonHolder.add(askBtn, gridBagConstraints);
        askBtn.setFont(ResourceManager.getFont("inter_regular.22"));
        askBtn.setForeground(ResourceManager.getColor("text_fg_dark"));

        answerButton.setBackground(getBackground());
        answerButton.setIcon(ResourceManager.getIcon("answer_default", ResourceManager.MINI));
        answerButton.setText("Answer");
        answerButton.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        answerButton.setBorderPainted(false);
        answerButton.setContentAreaFilled(false);
        answerButton.setFocusPainted(false);
        answerButton.setPressedIcon(ResourceManager.getIcon("answer_pressed", ResourceManager.MINI));
        answerButton.setRolloverIcon(ResourceManager.getIcon("answer_rollover", ResourceManager.MINI));
        answerButton.addActionListener(evt -> answerButtonActionPerformed(evt));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        buttonHolder.add(answerButton, gridBagConstraints);
        answerButton.setFont(ResourceManager.getFont("inter_regular.22"));
        answerButton.setForeground(ResourceManager.getColor("text_fg_dark"));

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new Insets(25, 25, 10, 25);
        add(buttonHolder, gridBagConstraints);

        displayAnswerBtn.setBackground(getBackground());
        displayAnswerBtn.setIcon(arrowDown[0]);
        displayAnswerBtn.setText("Hide Answers");
        displayAnswerBtn.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        displayAnswerBtn.setBorderPainted(false);
        displayAnswerBtn.setContentAreaFilled(false);
        displayAnswerBtn.setFocusPainted(false);
        displayAnswerBtn.setPressedIcon(arrowDown[1]);
        displayAnswerBtn.setRolloverIcon(arrowDown[2]);
        displayAnswerBtn.addActionListener(evt -> displayAnswerBtnActionPerformed(evt));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new Insets(10, 0, 25, 0);
        add(displayAnswerBtn, gridBagConstraints);
        displayAnswerBtn.setFont(ResourceManager.getFont("inter_regular.22"));
        displayAnswerBtn.setForeground(ResourceManager.getColor("text_fg_dark"));
    }

    private void profileBtnActionPerformed(ActionEvent evt) {
        QnAForum.setContent(ProfileBoard.init(userName.getText()));
    }

    private void askBtnActionPerformed(ActionEvent evt) {
        QnAForum.setContent(AskBoard.init(userName.getText(), userProfile.getName()));
    }

    private void answerButtonActionPerformed(ActionEvent evt) {
        QnABoard.answerCurrentQuestion();
    }

    private void displayAnswerBtnActionPerformed(ActionEvent evt) {

        boolean isVisible = QnABoard.CurrentInstance.toggleAnswerDisplay();

        if (isVisible) {
            displayAnswerBtn.setText("Hide Answers");
            displayAnswerBtn.setIcon(arrowDown[0]);
            displayAnswerBtn.setPressedIcon(arrowDown[1]);
            displayAnswerBtn.setRolloverIcon(arrowDown[2]);

            return;
        }

        displayAnswerBtn.setText("Show Answers");
        displayAnswerBtn.setIcon(arrowUp[0]);
        displayAnswerBtn.setPressedIcon(arrowUp[1]);
        displayAnswerBtn.setRolloverIcon(arrowUp[2]);
    }

    private void searchBtnActionPerformed(ActionEvent evt) {
        QnAForum.setContent(SearchBoard.init(getUsername(), getUserProfileIndex()));
    }
}

