/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QnAForumInterface;

import Resources.ResourceManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * @author AJ
 */
public class ProfilePane extends JPanel {

    // End of variables declaration//GEN-END:variables
    private static ProfilePane SELECTED_PANE;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel profileIcon;
    private CustomControls.RoundedJPanel roundedPane;

    /**
     * Creates new form chooseProfilePane
     */
    public ProfilePane() {
        initComponents();
    }

    public static ProfilePane create(Icon icon) {
        ProfilePane pane = new ProfilePane();
        pane.profileIcon.setIcon(icon);
        return pane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPane = new CustomControls.RoundedJPanel();
        profileIcon = new JLabel();

        setOpaque(false);
        addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                formMouseEntered(evt);
            }

            public void mouseExited(MouseEvent evt) {
                formMouseExited(evt);
            }

            public void mouseReleased(MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new BorderLayout());

        roundedPane.setBackground(ResourceManager.getColor("main_light"));
        roundedPane.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        roundedPane.setBorderColor(ResourceManager.getColor("main_dark"));
        roundedPane.setCornerRadius(180);
        roundedPane.setLimitRadius(false);
        roundedPane.setLayout(new BorderLayout());

        profileIcon.setHorizontalAlignment(SwingConstants.CENTER);
        roundedPane.add(profileIcon, BorderLayout.CENTER);

        add(roundedPane, BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(MouseEvent evt) {
        if (isSelected()) return;
        setColor(ResourceManager.getColor("accent"));
    }

    private void formMouseExited(MouseEvent evt) {
        if (isSelected()) return;
        setColor(ResourceManager.getColor("main_light"));
    }

    private void formMouseReleased(MouseEvent evt) {
        setSelected();
    }

    private void setColor(Color c) {
        roundedPane.setBackground(c);
    }

    public boolean isSelected() {
        if (SELECTED_PANE == null) return false;
        return SELECTED_PANE.equals(this);
    }

    public void setSelected() {
        if (isSelected()) return;

        if (SELECTED_PANE != null)
            SELECTED_PANE.setColor(ResourceManager.getColor("main_light"));
        SELECTED_PANE = this;
        setColor(ResourceManager.getColor("accent_dark"));
    }
}
