@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "BoardStructurePackage.Board",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1680547385 { 
   	label=BoardStructurePackage
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Board1680547385[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Board</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   frameSwitchContext: BoardFrameSwitchContext [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   main: MainFrame [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ refresh()</TD></TR>
<TR><TD ALIGN="LEFT" >+ requestSwitchFrame(frameName: String, switchContext: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

BoardFrame1680547385[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BoardFrame</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   boardPanels: Map&lt;String, Panel&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addPanel(panelName: String, panel: Panel)</TD></TR>
<TR><TD ALIGN="LEFT" >+ addPanel(panelName: String, panel: Panel, constraints: Object)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getPanel(panelName: String): Panel</TD></TR>
<TR><TD ALIGN="LEFT" >+ removePanel(panelName: String): Panel</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

BoardFrameSwitchContext1680547385[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BoardFrameSwitchContext</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   dataMap: Map&lt;String, String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dataRetriever: DataRetriever [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getContext(key: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ putContext(key: String, value: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ retrieveData(context: String): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

BoardPanel1680547385[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BoardPanel</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   frame: Frame [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addPanel(panelName: String, panel: Panel, constraints: Object)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getPanel(panelName: String): Panel</TD></TR>
<TR><TD ALIGN="LEFT" >+ removePanel(panelName: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MainFrame1680547385[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MainFrame</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   boardFrames: Map&lt;String, Frame&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   contentPane: Container [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addBoardFrame(frameName: String, frame: BoardFrame)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_93912729 { 
   	label=CustomControls
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   CustomJPanel93912729[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CustomJPanel</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cornerRadius: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   isRounded: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   limitRadius: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   shadowState: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># paintComponent(g: Graphics)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
Board1680547385 -> BoardFrame1680547385[arrowhead=none, arrowtail=empty, dir=both];
Board1680547385 -> BoardFrameSwitchContext1680547385[label="frameSwitchContext
[0..1]"];
Board1680547385 -> BoardPanel1680547385[arrowhead=none, arrowtail=empty, dir=both];
Board1680547385 -> MainFrame1680547385[label="main
[0..1]"];
BoardFrame1680547385 -> BoardPanel1680547385[arrowhead=none];
BoardFrame1680547385 -> BoardPanel1680547385[label="boardPanels
[0..*]", arrowhead=none];
BoardPanel1680547385 -> BoardFrame1680547385[label="frame
[0..1]", arrowhead=none];
CustomJPanel93912729 -> Board1680547385[arrowhead=none, arrowtail=empty, dir=both];
MainFrame1680547385 -> BoardFrame1680547385[label="boardFrames
[0..*]", arrowhead=none];
    
}
@enduml